[boilerplate] updated boilerplate stuff
Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>

diff --git a/utils/makefile.python b/utils/makefile.python
--- a/utils/makefile.python
+++ b/utils/makefile.python
@@ -41,19 +41,6 @@ ifeq ($(OS),Windows_NT)
 endif
 
 VTENV_OPTS ?=
-ifeq ($(PYTHON),python)
-  VIRTUALENV   = virtualenv
-else
-  VIRTUALENV   = virtualenv --python=$(PYTHON)
-endif
-
-ifeq ($(KBUILD_VERBOSE),1)
-  PIP_VERBOSE =
-  VIRTUALENV_VERBOSE =
-else
-  PIP_VERBOSE = "-q"
-  VIRTUALENV_VERBOSE = "-q"
-endif
 
 python-help::
 	@echo  'makefile.python:'
@@ -63,17 +50,18 @@ python-help::
 	@echo  '    pylint    - run pylint *linting*'
 	@echo  '    pytest    - run *tox* test on python objects'
 	@echo  '    pydebug   - run tests within a PDB debug session'
+	@echo  '    python    - run python interpreter from $(PY_ENV)/bin/python'
 	@echo  '    pybuild   - build python packages ($(PYDIST) $(PYBUILD))'
 	@echo  '    pyclean   - clean intermediate python objects'
 	@echo  '  targets using system users environment:'
 	@echo  '    py[un]install - [un]install python objects in editable mode'
 	@echo  '    upload-pypi   - upload $(PYDIST)/* files to PyPi'
 	@echo  'options:'
-	@echo  '  make PY=2  [targets] => to eval targets with python 2 ($(PY))'
-	@echo  '  make PIP_INST=       => to set/unset pip install options ($(PIP_INST))'
-	@echo  '  make TEST=.          => choose test from $(TEST_FOLDER) (default "." runs all)'
-	@echo  '  make DEBUG=          => target "debug": do not invoke PDB on errors'
-	@echo  '  make PY_SETUP_EXTRAS => also install extras_require from setup.py \[develop,test\]'
+	@echo  '  make PY=3.7 [targets] => to eval targets with python 3.7 ($(PY))'
+	@echo  '  make PIP_INST=        => to set/unset pip install options ($(PIP_INST))'
+	@echo  '  make TEST=.           => choose test from $(TEST_FOLDER) (default "." runs all)'
+	@echo  '  make DEBUG=           => target "debug": do not invoke PDB on errors'
+	@echo  '  make PY_SETUP_EXTRAS  => also install extras_require from setup.py \[develop,test\]'
 	@echo  '  when using target "pydebug", set breakpoints within py-source by adding::'
 	@echo  '    DEBUG()'
 
@@ -88,13 +76,31 @@ msg-python-exe:
   https://www.python.org or install it from your package\n\
   manager. On debian based OS these requirements are\n\
   installed by::\n\n\
-    sudo -H apt-get install $(PYTHON)\n" | $(FMT)
+    sudo -H add-apt-repository ppa:deadsnakes/ppa\n\
+    sudo -H apt update\n\
+    sudo -H apt-get install $(PYTHON) python$(PY)-venv\n"
 
 ifeq ($(shell which $(PYTHON) >/dev/null 2>&1; echo $$?), 1)
 python-exe: msg-python-exe
 	$(error The '$(PYTHON)' command was not found)
 else
 python-exe:
+	@:
+endif
+
+msg-pip-exe:
+	@echo "\n  $(PIP) is required\n\n\
+  Make sure you have updated pip installed, grab it from\n\
+  https://pip.pypa.io or install it from your package\n\
+  manager. On debian based OS these requirements are\n\
+  installed by::\n\n\
+    sudo -H apt-get install python$(PY)-pip\n" | $(FMT)
+
+ifeq ($(shell which $(PIP) >/dev/null 2>&1; echo $$?), 1)
+pip-exe: msg-pip-exe
+	$(error The '$(PIP)' command was not found)
+else
+pip-exe:
 	@:
 endif
 
@@ -108,7 +114,13 @@ quiet_cmd_pyinstall = INSTALL   $2
 
 # $2 path to folder with setup.py, this uses pip from pyenv (not OS!)
 quiet_cmd_pyenvinstall = PYENV     install $2
-      cmd_pyenvinstall = $(PY_ENV_BIN)/python -m pip $(PIP_VERBOSE) install -e $2$(PY_SETUP_EXTRAS)
+      cmd_pyenvinstall = \
+	if ! cat $(PY_ENV)/requirements.sha256 2>/dev/null | sha256sum --check --status 2>/dev/null; then \
+		$(PY_ENV_BIN)/python -m pip $(PIP_VERBOSE) install -e $2$(PY_SETUP_EXTRAS) ;\
+		sha256sum requirements*.txt > $(PY_ENV)/requirements.sha256 ;\
+	else \
+		echo "PYENV     $2 already installed"; \
+	fi
 
 # Uninstall the package.  Since pip does not uninstall the no longer needed
 # depencies (something like autoremove) the depencies remain.
@@ -125,7 +137,9 @@ quiet_cmd_pyenvuninstall = PYENV     uninstall   $2
 quiet_cmd_virtualenv  = PYENV     usage: $ source ./$@/bin/activate
       cmd_virtualenv  = \
 	if [ ! -d "./$(PY_ENV)" ];then                                  \
-		$(VIRTUALENV) $(VIRTUALENV_VERBOSE) $(VTENV_OPTS) $2;   \
+		$(PYTHON) -m venv $(VTENV_OPTS) $2;                     \
+		$(PY_ENV_BIN)/python -m pip install $(PIP_VERBOSE) -U pip wheel setuptools; \
+		$(PY_ENV_BIN)/python -m pip install $(PIP_VERBOSE) -r requirements.txt;     \
 	else                                                            \
 		echo "PYENV     using virtualenv from $2";              \
         fi
@@ -189,6 +203,7 @@ PHONY += pyuninstall
 pyuninstall: pip-exe
 	$(call cmd,pyuninstall,$(PYOBJECTS))
 
+# install / uninstall python objects into virtualenv (PYENV)
 # for installation use the pip from PY_ENV (not the OS)!
 PHONY += pyenvinstall
 pyenvinstall: $(PY_ENV)
@@ -206,8 +221,6 @@ pyclean:
 pyenv: $(PY_ENV)
 $(PY_ENV): python-exe
 	$(call cmd,virtualenv,$(PY_ENV))
-	$(Q)$(PY_ENV_BIN)/python -m pip install $(PIP_VERBOSE) -U pip wheel pip setuptools
-	$(Q)$(PY_ENV_BIN)/python -m pip install $(PIP_VERBOSE) -r requirements.txt
 
 PHONY += pylint-exe
 pylint-exe: $(PY_ENV)
@@ -233,16 +246,8 @@ PHONY += pydebug
 pydebug: $(PY_ENV)
 	DEBUG=$(DEBUG) $(PY_ENV_BIN)/pytest $(DEBUG) -v $(TEST_FOLDER)/$(TEST)
 
-# install / uninstall python objects into virtualenv (PYENV)
-pyenv-install: $(PY_ENV)
-	@$(PY_ENV_BIN)/python -m pip $(PIP_VERBOSE) install -e .
-	@echo "ACTIVATE  $(call normpath,$(PY_ENV_ACT)) "
-
-pyenv-uninstall: $(PY_ENV)
-	@$(PY_ENV_BIN)/python -m pip $(PIP_VERBOSE) uninstall --yes .
-
-# runs python interpreter from ./local/py<N>/bin/python
-pyenv-python: pyenv-install
+# run python interpreter from ./local/py<N>/bin/python
+python: pyenvinstall
 	$(PY_ENV_BIN)/python -i
 
 # With 'dependency_links=' setuptools supports dependencies on packages hosted
@@ -252,7 +257,7 @@ pyenv-python: pyenv-install
 # PyPi is required and since uploads via setuptools is not recommended, we have
 # to imstall / use twine ... its really a mess.
 #
-# [1] http://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi
+# [1] https://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi
 # [2] https://github.com/pypa/pip/pull/1519
 
 # https://github.com/pypa/twine
